### ISSUE TITLE
Rendering issues in CMD under Windows 10 (1709)

### ISSUE THREAD

**Issue by neelts** [haxeui/haxeui-pdcurses#1]
[Download code.zip](https://github.com/haxeui/haxeui-pdcurses/files/1521657/code.zip)

## Media
![default](https://user-images.githubusercontent.com/200919/33483880-f51e98ec-d6b0-11e7-9737-97087717fb39.png)

## Test app / minimal test case

compile.hxml is deduced from Build.xml in haxeui-pdcourses
(maybe it's wrong, i'm not sure because there is no example how to build it properly in repo)

> -cp src
> -main Main
> 
> -lib haxeui-core
> -lib haxeui-pdcurses
> 
> -D UNICODE
> -D _UNICODE
> -D wxMSVC_VERSION_AUTO
> -D WIN32=windows
> 
> -cpp out

## Your Environment
Latest git versions of haxeui-core and haxeui-pdcurses
Windows 10 (1709)

**Comment by ianharrigan** [comment]
Yeah, the compile looks fine... the problem is im using extended ascii characters to draw borders... I was worried this would happen. Though i am a little surprised that its happening on a windows machine. 

These are the character codes: https://github.com/haxeui/haxeui-pdcurses/blob/master/haxe/ui/backend/pdcurses/DrawHelper.hx#L8-L24

Can you try and play around there and see if something comes up?

**Comment by ianharrigan** [comment]
this is your test app on my system:

![image](https://user-images.githubusercontent.com/3024242/33484543-fce2a180-d6a2-11e7-8703-a1b9de034a85.png)

:(

**Comment by ianharrigan** [comment]
what does this show on your system?

```
trace("┌".charCodeAt(0));
```

**Comment by ianharrigan** [comment]
Can you pull the latest and try again? Im using the constants defined in `curses.h` now, so _maybe_ (hopefully) this will be more consistent now.

Let me know if that works.

Cheers,
Ian

**Comment by neelts** [comment]
Hello! Sorry for late answer, I checked last repo on my home laptop, works great!
But this issue was on my working PC, I could test again only on Monday.

**Comment by neelts** [comment]
And yes, it works finally, thanks Ian!
